// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ThuongMaiDienTuWebAPI.Models
{
    public partial class Account
    {
        public int AccountId { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string RoleId { get; set; }

        public virtual Employee PhoneNumber1 { get; set; }
        public virtual Customer PhoneNumberNavigation { get; set; }
        public virtual Role Role { get; set; }
    }
}