// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ThuongMaiDienTuWebAPI.Models
{
    public partial class Feature
    {
        public Feature()
        {
            ProductFeatures = new HashSet<ProductFeature>();
        }

        public int FeatureId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<ProductFeature> ProductFeatures { get; set; }
    }
}