// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ThuongMaiDienTuWebAPI.Models
{
    public partial class Price
    {
        public int PriceId { get; set; }
        public double ImportPrice { get; set; }
        public double Profit { get; set; }
        public DateTime ModifiedAt { get; set; }
        public string ProductId { get; set; }
        public int IsEffect { get; set; }

        public virtual Product Product { get; set; }
    }
}