// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ThuongMaiDienTuWebAPI.Models
{
    public partial class ProductArticle
    {
        public int ArticleId { get; set; }
        public string ProductId { get; set; }
        public string ArHeading { get; set; }
        public string ArContent { get; set; }
        public int EmployeeId { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
    }
}