// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ThuongMaiDienTuWebAPI.Models
{
    public partial class Review
    {
        public int ReviewId { get; set; }
        public int RatingPoint { get; set; }
        public string Comment { get; set; }
        public int OrderDetail { get; set; }

        public virtual OrderDetail OrderDetailNavigation { get; set; }
    }
}